### ISSUE TITLE
Release jbundler new version with bundle support version >= 2

### ISSUE THREAD

**Issue by pramod199** [mkristian/jbundler#102]
Hi,

when the new version of jbundler will get release which support [allow bundler >= 2](https://github.com/mkristian/jbundler/commit/d5a9256aa7112b4c3daf2f349bbe37f632c0b0eb)

**Comment by enebo** [comment]
@mkristian Any chance of getting a release out on this soon?

**Comment by mkristian** [comment]
I am offline over the weekend, will do this on Monday

On 6 May 2022 22:16:02 CEST, Thomas E Enebo ***@***.***> wrote:
***@***.*** Any chance of getting a release out on this soon?

**Comment by mkristian** [comment]
let's see if I did everything right . . . and not break anything. integration tests are beyond fixing as launching jruby from within maven needs more love from my side.

**Comment by JesseChavez** [comment]
I see a new version of `jbundler` which has `bundler > 1.5, < 3.0.0`

https://rubygems.org/gems/jbundler/versions/0.9.4

can we assume this issue is resolve and close this issue ?

**Comment by mkristian** [comment]
should be OK now to use with bundler 2.x
