### ISSUE TITLE
Include .jbundler in SCM/VCS?

### ISSUE THREAD

**Issue by aviflax** [mkristian/jbundler#67]
Hi, I’m new to Ruby and JRuby, so maybe this is obvious to others but I just don’t know: should I track the directory `.jbundler` in my source control repository? Or ignore it?

Thanks!

**Comment by mkristian** [comment]
I would say you should leave them out of version control. unless you have a special need for jbundler - like other tools using it - you should use https://github.com/mkristian/jar-dependencies which does not have such hidden configuration directory, comes with recent versions of jruby and has the same feature set as jbundler. in fact jbundler is more or less a wrapper around jar-dependencies.

**Comment by aviflax** [comment]
Thank you! I’m not sure if I definitely need JBundler but I’m using Warbler which does appear to have [special support for Bundler](https://github.com/jruby/warbler/tree/2.x-dev#jbundler-experimental):

> Applications that use JBundler, detected via presence of a `Jarfile`, will have the jars packaged up into the archive. the JBundler gem is ****not**** needed for runtime since all jars are already part of the classloader.

So I’m inclined to stick with JBundler for now.

Thanks!
