### ISSUE TITLE
jbundler a development gem?

### ISSUE THREAD

**Issue by thedebugger** [mkristian/jbundler#77]
README says that it is a development gem, but I had trouble loading jars until I add `require 'bundler'` in the code. Are docs old or am I doing something wrong? I also tried adding `Jars.require_jars_lock!`, but it looks for `Jars.lock` file which has a different format than Jarsfile.lock

**Comment by mkristian** [comment]
`require 'bundler'` sounds wrong, `require 'jbundler'` is needed - so the readme is wrong.

but you also can just use the `lock_jars` command which creates this `Jars.lock` file and then require it with `Jars.require_jars_lock!`. jar-dependency gem is a default gem with jruby and jbundler is using it under the hood.

**Comment by thedebugger** [comment]
Sorry, I meant 'jbundler'. Cool, I'll submit a PR to fix the documentation. Thanks!
