### ISSUE TITLE
error connecting to rubygems-proxy.torquebox.org when running jbundle install

### ISSUE THREAD

**Issue by mohamedhafez** [mkristian/jbundler#92]
When I run `jbundle install`, I get several errors like the following:

```
*** [err :: localhost] INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://rubygems-proxy.torquebox.org:80: Connection reset
```

**Comment by mohamedhafez** [comment]
in May bbrowning made [following comment](https://github.com/jruby-gradle/jruby-gradle-plugin/issues/349#issuecomment-496564438)

> The rubygems-proxy.torquebox.org server is unmaintained and has been that way for a few years. I'd strongly suggest anything referencing it point to something else.

@headius @enebo Perhaps [rubygems-servlets](https://github.com/torquebox/rubygems-servlets) could be hosted at rubygems-proxy.jruby.org or something to be sure its maintained, assuming enough people are using jbundler to include java maven libraries to warrant the effort?

**Comment by mohamedhafez** [comment]
Closing and opening an issue in the main JRuby repo

**Comment by headius** [comment]
We have officially adopted this server at a new address: mavengems.jruby.org

The old rubygems-proxy.torquebox.org address is also back up and running but it will go away. Please migrate to the new official address.

**Comment by RossBarnie** [comment]
FYI the domain has clearly been taken over by a bad actor as https://rubygems-proxy.torquebox.org now redirects to a Russian gambling site that automated tools like Symantec are flagging as a security risk:
```
org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://slotvulkanplay.ru:443: Connection reset
org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://slotvulkanplay.ru:443
^CERROR: 130
```
